# Generated by Django 4.1 on 2025-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.TextField(primary_key=True, serialize=False)),
                ('video_name', models.TextField()),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.TextField()),
                ('user_name', models.TextField()),
                ('user_location', models.TextField(null=True)),
                ('content', models.TextField()),
                ('gender', models.TextField(null=True)),
                ('user_level', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('reply_time', models.TextField()),
            ],
            options={
                'db_table': 'comments',
                'unique_together': {('video_id', 'user_name', 'content')},
            },
        ),
    ]
